/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "www.puravidasanantonio.com" },
      { protocol: "https", hostname: "avatarpreview.com" },
      { protocol: "https", hostname: "puravidasanantonio.net" },
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "www.ethosregen.com" },
      { protocol: "https", hostname: "i.ytimg.com" },
    ],
  },
  async redirects() {
    return [
      // ---- Old Doctible page URLs (45) ----
      { source: "/", destination: "/en", permanent: true },
      { source: "/infants-and-chiropractic", destination: "/en/services/infants-chiropractic", permanent: true },
      { source: "/el-mejor-quiropractico-san-antonio", destination: "/en/el-mejor-quiropractico-san-antonio", permanent: true },
      { source: "/auto-injury-chiropractor", destination: "/en/services/auto-injury", permanent: true },
      { source: "/san-antonio-quiropractico", destination: "/en/san-antonio-quiropractico", permanent: true },
      { source: "/ai-generated-content-disclaimer", destination: "/en/healthcare-disclaimer", permanent: true },
      { source: "/good-faith-estimate", destination: "/en/contact", permanent: true },
      { source: "/thank-you-form", destination: "/en/thank-you", permanent: true },
      { source: "/review-us", destination: "/en/testimonials", permanent: true },
      { source: "/chiropractic-care", destination: "/en/services/chiropractic-care", permanent: true },
      { source: "/blog", destination: "/en/blog", permanent: true },
      { source: "/new-patient-paperwork", destination: "/en/new-patient", permanent: true },
      { source: "/finding-a-chiropractor", destination: "/en/blog/first-chiropractic-visit-what-to-expect", permanent: true },
      { source: "/faq", destination: "/en/faq", permanent: true },
      { source: "/tmj", destination: "/en/conditions/tmj-jaw-pain", permanent: true },
      { source: "/neck-pain", destination: "/en/conditions/neck-pain", permanent: true },
      { source: "/sciatica", destination: "/en/conditions/sciatica", permanent: true },
      { source: "/headaches-migraines", destination: "/en/conditions/headaches", permanent: true },
      { source: "/back-pain", destination: "/en/conditions/lower-back-pain", permanent: true },
      { source: "/arm-leg-pain", destination: "/en/conditions/shoulder-arm-pain", permanent: true },
      { source: "/disc-injury", destination: "/en/conditions/disc-problems", permanent: true },
      { source: "/pregnancy-chiropractor", destination: "/en/services/pregnancy-chiropractor", permanent: true },
      { source: "/carpal-tunnel", destination: "/en/conditions/carpal-tunnel-syndrome", permanent: true },
      { source: "/scoliosis", destination: "/en/conditions/scoliosis", permanent: true },
      { source: "/shoulder-pain", destination: "/en/conditions/shoulder-arm-pain", permanent: true },
      { source: "/vertigo", destination: "/en/conditions/vertigo", permanent: true },
      { source: "/wellness-care", destination: "/en/services/wellness-care", permanent: true },
      { source: "/whiplash", destination: "/en/conditions/whiplash", permanent: true },
      { source: "/work-injury", destination: "/en/conditions/work-injuries", permanent: true },
      { source: "/anti-discrimination", destination: "/en/healthcare-disclaimer", permanent: true },
      { source: "/terms-service", destination: "/en/terms", permanent: true },
      { source: "/privacy-policy", destination: "/en/privacy-policy", permanent: true },
      { source: "/hipaa-privacy-policy", destination: "/en/privacy-policy", permanent: true },
      { source: "/healthcare-disclaimer", destination: "/en/healthcare-disclaimer", permanent: true },
      { source: "/accessibility", destination: "/en/healthcare-disclaimer", permanent: true },
      { source: "/contact-us", destination: "/en/contact", permanent: true },
      { source: "/testimonials", destination: "/en/testimonials", permanent: true },
      { source: "/office-tour", destination: "/en/about", permanent: true },
      { source: "/special", destination: "/en/new-patient", permanent: true },
      { source: "/us", destination: "/en/about", permanent: true },
      { source: "/describe-your-concern", destination: "/en/contact", permanent: true },
      { source: "/laser-therapy", destination: "/en/services/class-iv-laser", permanent: true },
      { source: "/shockwave-therapy", destination: "/en/services/shockwave-therapy", permanent: true },
      { source: "/softwave-therapy", destination: "/en/services/softwave-therapy", permanent: true },
      { source: "/pediatric-chiropractor", destination: "/en/services/pediatric-chiropractor", permanent: true },
      { source: "/contact", destination: "/en/contact", permanent: true },

      // ---- Old Doctible blog URLs (41) ----
      { source: "/blog/finding-chiropractor", destination: "/en/blog/first-chiropractic-visit-what-to-expect", permanent: true },
      { source: "/blog/4-reasons-choose-chiropractor", destination: "/en/blog/why-go-to-a-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractic-ok-pregnancy", destination: "/en/services/pregnancy-chiropractor", permanent: true },
      { source: "/blog/educational-requirements-chiropractor", destination: "/en/blog/what-does-a-chiropractor-do", permanent: true },
      { source: "/blog/chiropractic-care-back-pain", destination: "/en/blog/back-pain-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractor-can-help", destination: "/en/blog/conditions-we-treat", permanent: true },
      { source: "/blog/improve-golf-game-chiropractic", destination: "/en/conditions/sports-injury", permanent: true },
      { source: "/blog/choose-chiropractic-office", destination: "/en/blog/first-time-chiropractor-san-antonio", permanent: true },
      { source: "/blog/3-tips-chiropractor", destination: "/en/blog/first-chiropractic-visit-what-to-expect", permanent: true },
      { source: "/blog/chiropractor-explains-value-health", destination: "/en/blog/wellness-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractor-talks-bulging-discs", destination: "/en/blog/bulging-disc-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractor-discusses-herniated-discs", destination: "/en/blog/herniated-disc-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractors-may-help-scoliosis", destination: "/en/blog/scoliosis-chiropractor-san-antonio", permanent: true },
      { source: "/blog/choosing-chiropractor", destination: "/en/blog/first-time-chiropractor-san-antonio", permanent: true },
      { source: "/blog/fitness-tips-chiropractor", destination: "/en/conditions/sports-injury", permanent: true },
      { source: "/blog/chiropractor-discusses-different-types-headaches", destination: "/en/blog/headaches-migraines-chiropractor-san-antonio", permanent: true },
      { source: "/blog/headache-tips-chiropractic-office", destination: "/en/blog/headaches-migraines-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractic-care-can-help-joint-inflammation", destination: "/en/blog/joint-pain-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractors-may-help-tmj", destination: "/en/blog/a-doctor-s-perspective-on-tmj", permanent: true },
      { source: "/blog/chiropractic-care-helps-whiplash", destination: "/en/blog/whiplash-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractors-may-relieve-migraines", destination: "/en/blog/headaches-migraines-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractor-describes-stretching", destination: "/en/blog/wellness-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractors-help-range-motion", destination: "/en/blog/wellness-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractic-pregnancy", destination: "/en/services/pregnancy-chiropractor", permanent: true },
      { source: "/blog/chiropractic-treatment-car-accidents", destination: "/en/blog/san-antonio-chiropractor-car-accident", permanent: true },
      { source: "/blog/chiropractors-extensive-schooling", destination: "/en/blog/what-does-a-chiropractor-do", permanent: true },
      { source: "/blog/chiropractor-talks-headaches", destination: "/en/blog/headaches-migraines-chiropractor-san-antonio", permanent: true },
      { source: "/blog/athletes-improve-chiropractic-care", destination: "/en/conditions/sports-injury", permanent: true },
      { source: "/blog/achieve-healthier-spine", destination: "/en/blog/wellness-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractor-talks-wellness-care", destination: "/en/blog/wellness-chiropractor-san-antonio", permanent: true },
      { source: "/blog/sciatic-leg-pain", destination: "/en/blog/sciatica-chiropractor-san-antonio", permanent: true },
      { source: "/blog/time-improve-health", destination: "/en/blog/wellness-chiropractor-san-antonio", permanent: true },
      { source: "/blog/3-common-conditions-chiropractors-help", destination: "/en/blog/conditions-we-treat", permanent: true },
      { source: "/blog/car-accident-tips-chiropractor", destination: "/en/blog/san-antonio-chiropractor-car-accident", permanent: true },
      { source: "/blog/sitting-epidemic", destination: "/en/conditions/text-neck", permanent: true },
      { source: "/blog/looking-top-chiropractor", destination: "/en/blog/why-go-to-a-chiropractor-san-antonio", permanent: true },
      { source: "/blog/exercise-smarter", destination: "/en/blog/wellness-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractor-explains-avoid-back-injuries", destination: "/en/blog/back-pain-chiropractor-san-antonio", permanent: true },
      { source: "/blog/chiropractor-discusses-proper-child-backpacks", destination: "/en/blog/backpack-safety-kids-spine-san-antonio", permanent: true },
      { source: "/blog/just-back-pain", destination: "/en/blog/back-pain-chiropractor-san-antonio", permanent: true },
      { source: "/blog/back-pain-tips-chiropractor", destination: "/en/blog/back-pain-chiropractor-san-antonio", permanent: true },
    ];
  },
};

export default nextConfig;
